### ISSUE TITLE
Set yarn berry on ui directory and sub packages

### ISSUE THREAD

**Issue by 2wheeh** [MovieReviewComment/Mr.C#56]
### Content

`Yarn Berry` 의 workspace 기능을 사용하여 아래의 구조로 ui 디렉토리와 하위 패키지들을 재구성합니다.

```
.
├── MR-C.code-workspace
├── .github/
│   └── ...
├── api/
│   └── ...
└── ui/
    ├── .vscode
    ├── .yarn
    ├── tsconfig.base.json
    ├── pakcage.json 
    └── packages/
        ├── mr-c.app/
        │   ├── tsconfig.json
        │   ├── tailwind.config.ts
        │   └── ...
        ├── common-components/
        │   ├── tsconfig.json
        │   ├── tailwind.config.ts
        │   └── ...
        ├── common-utils/
        │   ├── tsconfig.json
        │   └── ...
        └── ...(more packages)
```

### Task
- [ ] mr-c.app 프로젝트 추가 (mr-c.app 이름은 추후 변경 가능)
- [ ] common-component 에 storybook 추가
- [ ] common-component 에 tailwindcss 적용
- [ ] common-utils 추가
