### ISSUE TITLE
Reconstruct UI test system

### ISSUE THREAD

**Issue by 2wheeh** [MovieReviewComment/Mr.C#58]
### Content
ui 디렉토리의 전체적인 구조가 변경되면서 (#48) 
#19 의 재작업이 필요합니다.

### Task
- [x] set up test on `mr-c.app`
- [x] set up test on `common-components`
- [x] set up test on `common-utils`
- [x] update script on `ui/package.json`
- [x] update readme

**Comment by 2wheeh** [comment]
라벨없이 PR 생성 후에 라벨을 추가 하는 경우에는 테스트 실행이 정상적으로 되지 않는 것을 확인했습니다. 

현재 워크플로를 트리거하는 이벤트로 `pull_request` 를 사용합니다. 이때 `pull request` 의 `Activity type` 을 별도로 지정하지 않아서 생기는 이슈입니다. `Activity types` 은 `default` 로  `opened`, `synchronize`,  `reopened` 3가지를 갖습니다. 따라서 PR 이 처음 생성되는 순간(`opened`) 설정된 라벨의 정보로 워크플로가 트리거되며, 개발자의 실수로 PR 생성할 때 라벨을 누락하고 나중에 라벨을 추가하는 경우에는 새로 워크플로가 트리거 되지 않습니다. (참고: [events-that-trigger-workflows](https://docs.github.com/ko/actions/using-workflows/events-that-trigger-workflows#pull_request))

가능한 해결방법은 다음의 2가지가 있습니다:
1. `Activity types` 에 `labeled` (와 `unlabeled`) 를 추가해서 라벨을 변경하는 경우에도 워크플로를 트리거하도록 수정한다.
2. 라벨이 아닌 `paths` 를 이용한 필터 설정으로 PR의 파일 경로를 통해 UI 테스트와 API 테스트를 구별한다. (참고: [triggering-a-workflow]( https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#using-filters-to-target-specific-paths-for-pull-request-or-push-events))
    
    이 경우 `api-test` 와 `ui-test` 워크플로 파일을 분리하고 아래처럼 paths를 설정하면 됩니다.
    ```yml
    on:
      pull_request:
        branches:
          - main
          - 'develop'
        paths:
          - 'ui/**' #(혹은 'api/**')
      workflow_dispatch:
    ```

개인적으로는 2번이 라벨을 누락하거나, 잘못 설정한 경우에도 정상적으로 워크플로를 트리거한다는 점에서 더 안정적인 것 같습니다. 다만 한 PR 에서 변경한 파일의 수가 300개가 넘어가면 정상적으로 워크플로를 트리거하지 못할 수 있다고 하네요. (참고: [git-diff-comparisons](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#git-diff-comparisons))

3번으로 1+2의 방법도 있겠네요.
의견 부탁드립니다. @isutare412 @skgndi12

**Comment by isutare412** [comment]
크 정확한 조사와 상세한 설명 너무 감사합니다! 👍 👍 👍 

저는 label 종속성을 떼어낼 수 있다는 점에서 2번이 좋아보이네요.

**Comment by isutare412** [comment]
> 다만 한 PR 에서 변경한 파일의 수가 300개가 넘어가면 정상적으로 워크플로를 트리거하지 못할 수 있다고 하네요.

저희 하우스룰이 변경사항 300라인 미만이라 파일수 300개가 넘어가는 케이스는 무시해도 좋을 것 같네요!

**Comment by skgndi12** [comment]
저도 2번 사항이 좋아보입니다. 편집한 파일의 경로를 기준으로 워크 플로우가 동작하는게 개발자의 휴먼 에러를 방지할 수 있을 것 같네요. 자세한 설명 감사합니다. 👍

**Comment by 2wheeh** [comment]
그럼 2번으로 하겠습니다. @skgndi12 API 테스트 워크플로에도 적용 부탁드립니다 🙂
